/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteProjectsRouteImport } from './routes/_site/projects'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteGamedevRouteImport } from './routes/_site/gamedev'
import { Route as SiteCertificatesRouteImport } from './routes/_site/certificates'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog/index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog/$slug'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGamedevRoute = SiteGamedevRouteImport.update({
  id: '/gamedev',
  path: '/gamedev',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCertificatesRoute = SiteCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof SiteIndexRoute
  '/links': typeof LinksRoute
  '/about': typeof SiteAboutRoute
  '/certificates': typeof SiteCertificatesRoute
  '/gamedev': typeof SiteGamedevRoute
  '/privacy': typeof SitePrivacyRoute
  '/projects': typeof SiteProjectsRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog/': typeof SiteBlogIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/links': typeof LinksRoute
  '/about': typeof SiteAboutRoute
  '/certificates': typeof SiteCertificatesRoute
  '/gamedev': typeof SiteGamedevRoute
  '/privacy': typeof SitePrivacyRoute
  '/projects': typeof SiteProjectsRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog': typeof SiteBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_site': typeof SiteRouteWithChildren
  '/links': typeof LinksRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/certificates': typeof SiteCertificatesRoute
  '/_site/gamedev': typeof SiteGamedevRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/links'
    | '/about'
    | '/certificates'
    | '/gamedev'
    | '/privacy'
    | '/projects'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/links'
    | '/about'
    | '/certificates'
    | '/gamedev'
    | '/privacy'
    | '/projects'
    | '/'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/$'
    | '/_site'
    | '/links'
    | '/_site/about'
    | '/_site/certificates'
    | '/_site/gamedev'
    | '/_site/privacy'
    | '/_site/projects'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  SiteRoute: typeof SiteRouteWithChildren
  LinksRoute: typeof LinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gamedev': {
      id: '/_site/gamedev'
      path: '/gamedev'
      fullPath: '/gamedev'
      preLoaderRoute: typeof SiteGamedevRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/certificates': {
      id: '/_site/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof SiteCertificatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCertificatesRoute: typeof SiteCertificatesRoute
  SiteGamedevRoute: typeof SiteGamedevRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCertificatesRoute: SiteCertificatesRoute,
  SiteGamedevRoute: SiteGamedevRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  SiteRoute: SiteRouteWithChildren,
  LinksRoute: LinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
